llm:
  model: "gemini-1.5-flash"
  embedding_model: "models/embedding-001"
  temperature: 0.5

chromadb:
  host: "localhost"
  port: 8000
  collection_name: "hospital_culture"

retry:
  stop_after_attempt: 3
  wait_fixed_seconds: 2

prompts:
  candidate_analyzer:
    system: "You are an expert HR analyst specializing in the medical field. Analyze the provided text and extract the candidate's professional traits. Your output must be a valid JSON object that conforms to the provided schema."
    human: |
      Please analyze the following candidate information:
      ---
      CANDIDATE BIO: {bio}
      ---
      PUBLIC CONTENT: {public_content}
      ---
      Based on the information, extract the required traits.
      {format_instructions}

  hospital_culture_extractor:
    system: |
      You are an expert analyst of healthcare organizational culture. 
      Use the provided context to extract the hospital's core values, work environment, and mission focus. 
      Your output must be a valid JSON object that conforms to the provided schema.
      CONTEXT: {context}
    human: "Based on the context, extract the hospital's cultural traits. {format_instructions}"

  trait_matching:
    system: "You are a trait-matching expert for clinical hiring. Compare the candidate's traits with the hospital's values. For each major trait, provide an alignment score from 0 (total mismatch) to 100 (perfect match) and a brief justification. Your output must be a valid JSON object containing a 'matches' key with a list of objects, conforming to the schema."
    human: |
      CANDIDATE TRAITS: {candidate_traits}
      HOSPITAL CULTURE: {hospital_culture}
      Please perform the trait matching.
      {format_instructions}

  conflict_risk_detector:
    system: "You are a risk detection specialist in HR. Based on the candidate's traits and the hospital's culture, identify potential 'soft clashes' or misalignments. Flag each risk as 'Red', 'Yellow', or 'Green'. Provide a justification for each. Your output must be a valid JSON object containing a 'risks' key with a list of objects."
    human: |
      CANDIDATE TRAITS: {candidate_traits}
      HOSPITAL CULTURE: {hospital_culture}
      Identify potential conflicts. For example, an 'independent' candidate in a 'hierarchical' hospital.
      {format_instructions}

  fit_index_generator:
    system: "You are a final decision analyst. Given the trait alignment scores and conflict risks, calculate a final 'Clinical Fit Index' score from 0 to 100 and write a concise summary. Your output must be a valid JSON object."
    human: |
      TRAIT MATCHES: {trait_matches}
      CONFLICT RISKS: {conflict_risks}
      Based on this data, generate the final score and summary.
      {format_instructions}